switch (global.char_selection){
    case 0:
        name="Jacob NSOD"
        height="1,78 m"
        weight="76 kg"
        weapon="Great Sword"
        abilities="Dodge Roll"
        strength="Medium"
        vitality="Medium"
        resistance="Medium"
        agility="Medium"
        break;
    case 1:
        name="Harlow Barone"
        height="1.84 m"
        weight="78 kg"
        weapon="Great Hammer"
        abilities="Dodge Roll"
        strength="Highest"
        vitality="Medium High"
        resistance="Medium Low"
        agility="Medium Low"
        break;
    case 2:
        name="Brenton Guillory"
        height="1.88 m"
        weight="74 kg"
        weapon="Pistol"
        abilities="Dodge Roll"
        strength="High"
        vitality="Medium"
        resistance="Medium High"
        agility="High"
        break;
    case 3:
        name="Penelope Darrow"
        height="1.60 m"
        weight="54 kg"
        weapon="Bow"
        abilities="Dodge Roll"
        strength="Medium High"
        vitality="Medium"
        resistance="Medium"
        agility="Medium High"
        break;     
    case 4:
        name="Luna Von Brandt"
        height="1.70 m"
        weight="65 kg"
        weapon="Magic"
        abilities="Dodge Roll"
        strength="High"
        vitality="Medium Low"
        resistance="Medium High"
        agility="Medium"
        break;    
    case 5:
        name="Mahli Ueno"
        height="1.75 m"
        weight="75 kg"
        weapon="None"
        abilities="Dodge Roll"
        strength="Medium"
        vitality="Medium"
        resistance="Medium"
        agility="Medium"
        break;    
    case 6:
        name="Thalia Fowler"
        height="1.73 m"
        weight="56 kg"
        weapon="Magic Daggers"
        abilities="Dodge Roll"
        strength="High"
        vitality="Medium Low"
        resistance="Medium"
        agility="High"
        break;
    case 7:
        name="Alexis Stenberg"
        height="1.68 m"
        weight="60 kg"
        weapon="Shield"
        abilities="Dodge Roll"
        strength="Medium"
        vitality="High"
        resistance="High"
        agility="Low"
        break;    
    case 8: 
        name="Zimri Pointdestre"
        height="1.75 m"
        weight="70 kg"
        weapon="Guitar"
        abilities="Dodge Roll"
        strength="High"
        vitality="Medium"
        resistance="Medium Low"
        agility="Medium"
        break; 
    case 9:
        name="Euphemia Vela"
        height="1.72 m"
        weight="59 kg"
        weapon="Spear"
        abilities="Dodge Roll"
        strength="High"
        vitality="Medium"
        resistance="Medium Low"
        agility="Medium High"
        break;    
    case 10:
        name="Straton Riese"
        height="1.68 m"
        weight="74 kg"
        weapon="Sword and Shield"
        abilities="Dodge Roll"
        strength="Medium"
        vitality="Medium High"
        resistance="Medium"
        agility="Medium Low"
        break;     
    case 11:
        name="Dorothea Alma"
        height="1.72 m"
        weight="60 kg"
        weapon="Blessings"
        abilities="Dodge Roll"
        strength="High"
        vitality="Medium"
        resistance="High"
        agility="Medium"
        break;   
    case 12:
        name="Orpheus Teufel"
        height="1.70 m"
        weight="73 kg"
        weapon="Curses"
        abilities="Dodge Roll"
        strength="High"
        vitality="Medium"
        resistance="Medium"
        agility="Medium High"
        break;  
}
