// Initialise the global array that allows the lookup of the depth of a given object
// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
// NOTE: MacroExpansion is used to insert the array initialisation at import time
gml_pragma( "global", "__global_object_depths()");

// insert the generated arrays here
global.__objectDepths[0] = 10001; // obj_floor
global.__objectDepths[1] = 0; // obj_barrel
global.__objectDepths[2] = 0; // obj_chest
global.__objectDepths[3] = 3; // obj_door_u
global.__objectDepths[4] = 4; // obj_wall_up
global.__objectDepths[5] = -2; // obj_door_d
global.__objectDepths[6] = -50000000; // obj_wall_right
global.__objectDepths[7] = -1000000; // obj_wall_down
global.__objectDepths[8] = 0; // obj_bdoor
global.__objectDepths[9] = 0; // obj_door_r
global.__objectDepths[10] = 0; // obj_dungeon_wall
global.__objectDepths[11] = 0; // obj_door_l
global.__objectDepths[12] = 0; // obj_pedestal
global.__objectDepths[13] = 1; // obj_wall_left
global.__objectDepths[14] = 4; // obj_rock
global.__objectDepths[15] = 0; // obj_vase
global.__objectDepths[16] = 0; // obj_crate
global.__objectDepths[17] = 0; // obj_fheart
global.__objectDepths[18] = 0; // obj_torch
global.__objectDepths[19] = 0; // obj_hheart
global.__objectDepths[20] = 0; // obj_CH_deer_brock
global.__objectDepths[21] = 0; // obj_solid_parent
global.__objectDepths[22] = 0; // obj_lifeform_parent
global.__objectDepths[23] = 0; // obj_door_parent
global.__objectDepths[24] = 0; // obj_equipable
global.__objectDepths[25] = 0; // obj_ppoff
global.__objectDepths[26] = 0; // obj_gen_controller
global.__objectDepths[27] = -1569325055; // obj_ps_controller
global.__objectDepths[28] = 0; // obj_view
global.__objectDepths[29] = 0; // obj_ppon
global.__objectDepths[30] = -10000; // obj_gui
global.__objectDepths[31] = 0; // obj_CH_tree_state
global.__objectDepths[32] = 0; // obj_CH_root
global.__objectDepths[33] = 0; // obj_green_puff
global.__objectDepths[34] = 0; // obj_tumey_3
global.__objectDepths[35] = 0; // obj_CH_deer_state
global.__objectDepths[36] = 0; // obj_CH_rcones
global.__objectDepths[37] = 0; // obj_CH_leaf
global.__objectDepths[38] = 0; // obj_CH_rm_bk
global.__objectDepths[39] = -1000; // obj_bt_bullet
global.__objectDepths[40] = 0; // obj_tumey_2
global.__objectDepths[41] = 99990; // obj_CH_deer_brocks
global.__objectDepths[42] = 0; // obj_tumey_1
global.__objectDepths[43] = 0; // obj_CH_groots
global.__objectDepths[44] = 0; // obj_CH_rcone
global.__objectDepths[45] = 0; // obj_fln_rock
global.__objectDepths[46] = 99990; // obj_fln_rock_shadow
global.__objectDepths[47] = -100000; // obj_kb
global.__objectDepths[48] = 0; // obj_enemy
global.__objectDepths[49] = 1; // obj_head
global.__objectDepths[50] = 0; // obj_slm_bullet
global.__objectDepths[51] = -1002; // obj_swing
global.__objectDepths[52] = 2; // obj_body
global.__objectDepths[53] = 0; // obj_blue_puff
global.__objectDepths[54] = 3; // obj_sword
global.__objectDepths[55] = 0; // obj_pglobs
global.__objectDepths[56] = 0; // obj_slm_a
global.__objectDepths[57] = -500; // obj_sword_t
global.__objectDepths[58] = 0; // obj_slm_b
global.__objectDepths[59] = 0; // obj_roll
global.__objectDepths[60] = 0; // obj_skull
global.__objectDepths[61] = 0; // obj_red_puff
global.__objectDepths[62] = -900; // obj_explosion
global.__objectDepths[63] = 0; // obj_skull_n
global.__objectDepths[64] = 0; // obj_e_arrow
global.__objectDepths[65] = 0; // obj_creep
global.__objectDepths[66] = 0; // obj_psnt_arch_body
global.__objectDepths[67] = 0; // object26
global.__objectDepths[68] = 0; // obj_psnt_body
global.__objectDepths[69] = 0; // obj_mimic
global.__objectDepths[70] = 1; // obj_psnt_head
global.__objectDepths[71] = 0; // obj_cadaver
global.__objectDepths[72] = 0; // obj_skull_fl_n
global.__objectDepths[73] = 1; // obj_psnt_arch_head
global.__objectDepths[74] = 0; // obj_skull_fl
global.__objectDepths[75] = 3; // obj_stick
global.__objectDepths[76] = -1002; // obj_e_swing
global.__objectDepths[77] = 3; // obj_e_bow
global.__objectDepths[78] = 0; // obj_bat
global.__objectDepths[79] = 0; // obj_slm_cr
global.__objectDepths[80] = 0; // obj_menu2_options
global.__objectDepths[81] = 0; // obj_menu2_controls
global.__objectDepths[82] = 0; // obj_menu2_swords
global.__objectDepths[83] = 0; // obj_menu2_video2
global.__objectDepths[84] = 0; // obj_menu2_lg
global.__objectDepths[85] = 0; // obj_menu2_video
global.__objectDepths[86] = 0; // obj_menu2_fs
global.__objectDepths[87] = -400; // obj_menu2_audio2
global.__objectDepths[88] = 0; // obj_menu2_state1
global.__objectDepths[89] = 0; // obj_menu2_mvolume
global.__objectDepths[90] = 0; // obj_menu2_back
global.__objectDepths[91] = 0; // obj_menu2_slider1
global.__objectDepths[92] = 0; // obj_menu2_sfxvolume
global.__objectDepths[93] = 0; // obj_menu2_slider2
global.__objectDepths[94] = 0; // obj_menu2_audio
global.__objectDepths[95] = -20; // obj_menu2_state0
global.__objectDepths[96] = -200; // obj_blackout
global.__objectDepths[97] = 0; // obj_menu2_state2
global.__objectDepths[98] = -6; // obj_walltile_down
global.__objectDepths[99] = 0; // obj_menu2_controles
global.__objectDepths[100] = 0; // obj_walltile_up
global.__objectDepths[101] = -15; // obj_title
global.__objectDepths[102] = -20; // obj_menu1
global.__objectDepths[103] = -6; // obj_walltile_left
global.__objectDepths[104] = 10000; // obj_fl_up
global.__objectDepths[105] = -6; // obj_walltile_right
global.__objectDepths[106] = -10; // obj_cutscene
global.__objectDepths[107] = 100; // obj_background1
global.__objectDepths[108] = 0; // obj_menu2_state3
global.__objectDepths[109] = -100; // obj_quit
global.__objectDepths[110] = 0; // obj_menu
global.__objectDepths[111] = 0; // obj_menu2_controls2
global.__objectDepths[112] = 10000; // obj_fl_rg
global.__objectDepths[113] = 0; // object121
global.__objectDepths[114] = 10000; // obj_fl_dn
global.__objectDepths[115] = 10000; // obj_fl_cn
global.__objectDepths[116] = 0; // obj_infosheet
global.__objectDepths[117] = 0; // obj_charselect_ctrl
global.__objectDepths[118] = -20; // obj_bdesign
global.__objectDepths[119] = -40; // obj_enterbtn
global.__objectDepths[120] = 0; // obj_back
global.__objectDepths[121] = 0; // obj_p
global.__objectDepths[122] = -10; // obj_banner
global.__objectDepths[123] = 0; // object122
global.__objectDepths[124] = 0; // object123
global.__objectDepths[125] = -30; // obj_charpresent
global.__objectDepths[126] = -40; // obj_nextbtn
global.__objectDepths[127] = 10000; // obj_fl_lf
global.__objectDepths[128] = -1569325055; // obj_cursor


global.__objectNames[0] = "obj_floor";
global.__objectNames[1] = "obj_barrel";
global.__objectNames[2] = "obj_chest";
global.__objectNames[3] = "obj_door_u";
global.__objectNames[4] = "obj_wall_up";
global.__objectNames[5] = "obj_door_d";
global.__objectNames[6] = "obj_wall_right";
global.__objectNames[7] = "obj_wall_down";
global.__objectNames[8] = "obj_bdoor";
global.__objectNames[9] = "obj_door_r";
global.__objectNames[10] = "obj_dungeon_wall";
global.__objectNames[11] = "obj_door_l";
global.__objectNames[12] = "obj_pedestal";
global.__objectNames[13] = "obj_wall_left";
global.__objectNames[14] = "obj_rock";
global.__objectNames[15] = "obj_vase";
global.__objectNames[16] = "obj_crate";
global.__objectNames[17] = "obj_fheart";
global.__objectNames[18] = "obj_torch";
global.__objectNames[19] = "obj_hheart";
global.__objectNames[20] = "obj_CH_deer_brock";
global.__objectNames[21] = "obj_solid_parent";
global.__objectNames[22] = "obj_lifeform_parent";
global.__objectNames[23] = "obj_door_parent";
global.__objectNames[24] = "obj_equipable";
global.__objectNames[25] = "obj_ppoff";
global.__objectNames[26] = "obj_gen_controller";
global.__objectNames[27] = "obj_ps_controller";
global.__objectNames[28] = "obj_view";
global.__objectNames[29] = "obj_ppon";
global.__objectNames[30] = "obj_gui";
global.__objectNames[31] = "obj_CH_tree_state";
global.__objectNames[32] = "obj_CH_root";
global.__objectNames[33] = "obj_green_puff";
global.__objectNames[34] = "obj_tumey_3";
global.__objectNames[35] = "obj_CH_deer_state";
global.__objectNames[36] = "obj_CH_rcones";
global.__objectNames[37] = "obj_CH_leaf";
global.__objectNames[38] = "obj_CH_rm_bk";
global.__objectNames[39] = "obj_bt_bullet";
global.__objectNames[40] = "obj_tumey_2";
global.__objectNames[41] = "obj_CH_deer_brocks";
global.__objectNames[42] = "obj_tumey_1";
global.__objectNames[43] = "obj_CH_groots";
global.__objectNames[44] = "obj_CH_rcone";
global.__objectNames[45] = "obj_fln_rock";
global.__objectNames[46] = "obj_fln_rock_shadow";
global.__objectNames[47] = "obj_kb";
global.__objectNames[48] = "obj_enemy";
global.__objectNames[49] = "obj_head";
global.__objectNames[50] = "obj_slm_bullet";
global.__objectNames[51] = "obj_swing";
global.__objectNames[52] = "obj_body";
global.__objectNames[53] = "obj_blue_puff";
global.__objectNames[54] = "obj_sword";
global.__objectNames[55] = "obj_pglobs";
global.__objectNames[56] = "obj_slm_a";
global.__objectNames[57] = "obj_sword_t";
global.__objectNames[58] = "obj_slm_b";
global.__objectNames[59] = "obj_roll";
global.__objectNames[60] = "obj_skull";
global.__objectNames[61] = "obj_red_puff";
global.__objectNames[62] = "obj_explosion";
global.__objectNames[63] = "obj_skull_n";
global.__objectNames[64] = "obj_e_arrow";
global.__objectNames[65] = "obj_creep";
global.__objectNames[66] = "obj_psnt_arch_body";
global.__objectNames[67] = "object26";
global.__objectNames[68] = "obj_psnt_body";
global.__objectNames[69] = "obj_mimic";
global.__objectNames[70] = "obj_psnt_head";
global.__objectNames[71] = "obj_cadaver";
global.__objectNames[72] = "obj_skull_fl_n";
global.__objectNames[73] = "obj_psnt_arch_head";
global.__objectNames[74] = "obj_skull_fl";
global.__objectNames[75] = "obj_stick";
global.__objectNames[76] = "obj_e_swing";
global.__objectNames[77] = "obj_e_bow";
global.__objectNames[78] = "obj_bat";
global.__objectNames[79] = "obj_slm_cr";
global.__objectNames[80] = "obj_menu2_options";
global.__objectNames[81] = "obj_menu2_controls";
global.__objectNames[82] = "obj_menu2_swords";
global.__objectNames[83] = "obj_menu2_video2";
global.__objectNames[84] = "obj_menu2_lg";
global.__objectNames[85] = "obj_menu2_video";
global.__objectNames[86] = "obj_menu2_fs";
global.__objectNames[87] = "obj_menu2_audio2";
global.__objectNames[88] = "obj_menu2_state1";
global.__objectNames[89] = "obj_menu2_mvolume";
global.__objectNames[90] = "obj_menu2_back";
global.__objectNames[91] = "obj_menu2_slider1";
global.__objectNames[92] = "obj_menu2_sfxvolume";
global.__objectNames[93] = "obj_menu2_slider2";
global.__objectNames[94] = "obj_menu2_audio";
global.__objectNames[95] = "obj_menu2_state0";
global.__objectNames[96] = "obj_blackout";
global.__objectNames[97] = "obj_menu2_state2";
global.__objectNames[98] = "obj_walltile_down";
global.__objectNames[99] = "obj_menu2_controles";
global.__objectNames[100] = "obj_walltile_up";
global.__objectNames[101] = "obj_title";
global.__objectNames[102] = "obj_menu1";
global.__objectNames[103] = "obj_walltile_left";
global.__objectNames[104] = "obj_fl_up";
global.__objectNames[105] = "obj_walltile_right";
global.__objectNames[106] = "obj_cutscene";
global.__objectNames[107] = "obj_background1";
global.__objectNames[108] = "obj_menu2_state3";
global.__objectNames[109] = "obj_quit";
global.__objectNames[110] = "obj_menu";
global.__objectNames[111] = "obj_menu2_controls2";
global.__objectNames[112] = "obj_fl_rg";
global.__objectNames[113] = "object121";
global.__objectNames[114] = "obj_fl_dn";
global.__objectNames[115] = "obj_fl_cn";
global.__objectNames[116] = "obj_infosheet";
global.__objectNames[117] = "obj_charselect_ctrl";
global.__objectNames[118] = "obj_bdesign";
global.__objectNames[119] = "obj_enterbtn";
global.__objectNames[120] = "obj_back";
global.__objectNames[121] = "obj_p";
global.__objectNames[122] = "obj_banner";
global.__objectNames[123] = "object122";
global.__objectNames[124] = "object123";
global.__objectNames[125] = "obj_charpresent";
global.__objectNames[126] = "obj_nextbtn";
global.__objectNames[127] = "obj_fl_lf";
global.__objectNames[128] = "obj_cursor";


// create another array that has the correct entries
var len = array_length_1d(global.__objectDepths);
global.__objectID2Depth = [];
for( var i=0; i<len; ++i ) {
	var objID = asset_get_index( global.__objectNames[i] );
	if (objID >= 0) {
		global.__objectID2Depth[ objID ] = global.__objectDepths[i];
	} // end if
} // end for